### ISSUE TITLE
Different inventory groups for different gamemodes

### ISSUE THREAD

**Issue by Cyanoure** [K0bus/CreativeManager#27]
It would be nice to have a grouping system.
I would like to use the same inventory for adventure and survival modes.

An example config:
```yaml
# gamemode: what-inventory-to-use
inventory:
  creative: creative
  adventure: survival
  survival: survival
# Instead of false: creative: ignore
```
